---
title: "Beta-diversity analysis"
subtitle: "Where we analyse the effect of a factor on shared diversity"
date: last-modified
author:
  - name: Adrien Taudière
    url: https://adrientaudiere.github.io/bioinfo.starter/analysis/02_alpha_diversity.qmd
    affiliation: IdEst
    affiliation-url: https://orcid.org/my-orcid?orcid=0000-0003-1088-1182
    citation: true
params:
  factor_of_interest: "Type"
# bibliography: bibliography.bib
# link-citations: true
---

See the documentation of the `MiscMetabar` package for example of [btea diversity analysis](https://adrientaudiere.github.io/MiscMetabar/articles/beta-div.html). 

```{r}
if(base::interactive()) {
  params <- rmarkdown::yaml_front_matter(here::here("analysis/03_beta_diversity.qmd"))$params
}
factor_of_interest <- params$factor_of_interest
```

```{r,  message=FALSE, warning=FALSE}
library(knitr)
library(targets)
library(MiscMetabar)
here::i_am("analysis/03_beta_diversity.qmd")
source(here::here("R/styles.R"))
```

```{r}
d_pq <- clean_pq(tar_read("d_vs", store=here::here("_targets/")))
```


```{r}
#| error: true
formattable_pq(
    subset_samples(d_pq, Type %in% c("Mix", "Mono")),
    factor_of_interest,
    min_nb_seq_taxa = 1000, 
    lev_col_taxa = "Family",
    taxonomic_levels=c("Order", "Family", "Genus"),
    log10trans = TRUE,

  )
```

```{r}
library("vegan")
plot_ordination(d_pq, vegan::decorana(vegdist(as(otu_table(d_pq), "matrix"),
    method = "robust.aitchison"
  )), color = factor_of_interest) +
  geom_point(size = 3) +
  stat_ellipse(inherit.aes = F, aes(x = DCA1, y = DCA2, linetype = .data[[factor_of_interest]], col = .data[[factor_of_interest]])) + theme_idest() + scale_color_manual(values=idest_pal$dark_color_idest[[1]][c(5,4,2)])
```


```{r}
adonis_pq(subset_samples(d_pq, Type %in% c("Mix", "Mono")), factor_of_interest, na_remove = TRUE, correction_for_sample_size = TRUE, by = "terms")
```


```{r}
d_pq |>
  subset_samples(Type %in% c("Mix", "Mono")) |>
biplot_pq(merge_sample_by = factor_of_interest, rarefy_after_merging = T)
```


```{r}
res_var <- var_par_rarperm_pq(
    subset_samples(d_pq, Type %in% c("Mix", "Mono")),
    list_component = list(
      "Tmt" = c("Tmt"),
      "Bloc" = c("Bloc"),
      "Type" = c("Type")
    ),
    nperm = 9,
    dbrda_computation = TRUE
  )

plot_var_part_pq(res_var)
`````````


{{< include _session_info.qmd >}}
