---
title: "Bioinformatics pipeline summary"
subtitle: "Where we see the pipeline processes"
date: last-modified
author:
  - name: Adrien Taudière
    url: https://adrientaudiere.github.io/bioinfo.starter/analysis/01_bioinformatics.qmd
    affiliation: IdEst
    affiliation-url: https://orcid.org/my-orcid?orcid=0000-0003-1088-1182
citation: true
---

```{r}
#| message: false
#| warning: false
library(knitr)
library(targets)
library(MiscMetabar)
library(divent)
here::i_am("analysis/04_fist_exploration.qmd")
devtools::load_all("~/Nextcloud/IdEst/Projets/pqverse/pqverse_pkg/MiscMetabar")
devtools::load_all("~/Nextcloud/IdEst/Projets/pqverse/pqverse_pkg/comparpq")
devtools::load_all("~/Nextcloud/IdEst/Projets/pqverse/pqverse_pkg/tidypq")
devtools::load_all("~/Nextcloud/IdEst/Projets/pqverse/pqverse_pkg/ggplotpq")

source(here::here("R/functions.R"))
source(here::here("R/styles.R"))
```


```{r child="../R/styles.qmd"}

```

```{r}
d_16S <- readRDS(here::here("data/data_final/d_16S.rds"))
d_16S <- simplify_taxo(d_16S, pattern_to_NA = "_X+$|_sp\\.$")
d_pmoA <- readRDS(here::here("data/data_final/d_pmoA.rds"))
d_mcrA <- readRDS(here::here("data/data_final/d_mcrA.rds"))
```


```{r}
d_3 <- comparpq::list_phyloseq( list("16S" = d_16S, "pmoA" = d_pmoA, "mcrA" = d_mcrA), compute_dist=FALSE)
```


```{r}
comparpq::estim_diff_pq(d_16S, "Humidity")
gg_bubbles_pq(d_16S, facet_by = "Humidity") + no_legend()
```


```{r}
hill_curves_pq(d_16S, "Humidity", one_plot = TRUE) + theme_idest() + no_legend()
MiscMetabar::ggbetween_pq(d_16S, q = c(0, 1), "Humidity", one_plot = TRUE) + theme_idest() + no_legend()
MiscMetabar::ggbetween_pq(d_16S, q = 1, "Agricultural_practices", one_plot = TRUE) + theme_idest() + no_legend()
MiscMetabar::ggbetween_pq(d_16S, q = 1, "Site", one_plot = TRUE) + theme_idest() + no_legend()
```


```{r}
(d_16S |> tidypq::filter_samples_pq(!is.na(Humidity)) |>tax_bar_pq("Humidity", taxa="Phylum", add_ribbon = TRUE, percent_bar = TRUE) + theme_idest() + no_legend() +ylab("Proportion of sequences") + reorder_distinct_colors(alternate_lightness = TRUE)) +
  (d_16S |> tidypq::filter_samples_pq(!is.na(Humidity)) |>tax_bar_pq("Humidity", taxa="Phylum", add_ribbon = TRUE,  nb_seq=FALSE) + ylab("Number of ASV") +theme_idest() + no_legend()+ reorder_distinct_colors(alternate_lightness = TRUE)) 
```

```{r}
(d_16S |> 
  tidypq::filter_samples_pq(!is.na(Humidity)) |>
  tidypq::filter_taxa_pq(!is.na(Class_KSGP))|>
  tax_bar_pq("Humidity", taxa="Phylum", percent_bar = TRUE, add_ribbon = TRUE) + 
  ylab("Proportion of sequences") +
    theme_idest() +
     no_legend()+ reorder_distinct_colors(alternate_lightness = TRUE)) +
  (d_16S |> tidypq::filter_samples_pq(!is.na(Humidity)) |>
    tidypq::filter_taxa_pq(!is.na(Class_KSGP))|>
  tax_bar_pq("Humidity", taxa="Phylum", nb_seq=FALSE, add_ribbon = TRUE, ) +
   theme_idest() + 
   ylab("Number of OTU") +
   reorder_distinct_colors(alternate_lightness = TRUE)) 
```



```{r}
res_ancombc <- d_16S |> 
  tidypq::filter_samples_pq(!is.na(Humidity)) |>
  ancombc_pq(fact="Humidity", tax_level=NULL)
```


```{r}
ggplot(
    res_ancombc$res,
    aes(
      y = reorder(taxon, lfc_HumidityH),
      x = lfc_HumidityH,
      color = diff_HumidityH
    )
  ) +
    geom_vline(xintercept = 0) +
    geom_segment(aes(
      xend = 0, y = reorder(taxon, lfc_HumidityH),
      yend = reorder(taxon, lfc_HumidityH)
    ), color = "darkgrey") +
    geom_point()
```